#pragma kernel CSMain

struct GrassData {
    float3 position;
};

RWStructuredBuffer<GrassData> _datas;
int _grassAmountPerRow;
float _grassDensity;

[numthreads(8,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    GrassData grass;
    grass.position = float3(id.x%_grassAmountPerRow,1.0, id.x/_grassAmountPerRow);
    grass.position -= float3(_grassAmountPerRow/2,0.0,_grassAmountPerRow/2);
    grass.position *=  1/_grassDensity;
    _datas[id.x] = grass;
}
